- name: "asif ali"
  dob: "26-01-2003"
  moblienumber: 123456789
  addresses:
  - doorno: 101-120
    street: "vengal rao nagar" 
    town: sathupalli
    type: pm


- name: "ramesh"
  dob: "19-02-2004"
  moblienumber: 12365480
  addresses:
  - doorno: 129
    street: "gandhi nagar"
    town: sathupalli
    type: current
